#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# BSYHC - Base SisYpH Compiler
#
# Usage:
#   Compile:      python3 bsyhc.py -i b.syh -c -o bsyhc-test-b.py
#   Decompile:    python3 bsyhc.py -i bsyhc-test-b.py -d -o b-de.syh
#   Interpret:    python3 bsyhc.py -i b.syh
#
# Flags:
#   -i, --input FILE   input file (may be repeated to compile several files)
#   -o, --output FILE  output file
#   -c, --compile      compile .syh into a self-contained .py
#   -d, --decompile    decompile a compiled .py back into .syh
#   --merge MODE       how to merge several inputs: concat (default) or include
#   --split            decompile each source file separately (into -o directory)
#   -h, --help         show this help

import argparse
import ast
import os
import re
import sys

VERSION = "1.0.0"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
INTERPRETER_FILE = os.path.join(BASE_DIR, "main.py")


def bsyhc_error(message: str):
    print(f"BSYHC Error: {message}")
    sys.exit(1)


def read_lines(path: str) -> list:
    if not os.path.isfile(path):
        bsyhc_error(f"File '{path}' not found.")
    with open(path, "r", encoding="utf-8") as f:
        return f.read().splitlines()


def strip_main_block(source: str) -> str:
    match = re.search(r"^if __name__ == [\"']__main__[\"']:.*$", source, re.MULTILINE)
    if match:
        return source[: match.start()].rstrip() + "\n"
    return source


def load_interpreter() -> dict:
    if not os.path.isfile(INTERPRETER_FILE):
        bsyhc_error(f"Interpreter file '{INTERPRETER_FILE}' not found.")
    with open(INTERPRETER_FILE, "r", encoding="utf-8") as f:
        source = strip_main_block(f.read())
    namespace = {"__name__": "bsyhc_embedded_interpreter"}
    exec(compile(source, INTERPRETER_FILE, "exec"), namespace)
    return namespace


def merge_sources(inputs: list, mode: str) -> tuple:
    merged = []
    boundaries = []
    for index, path in enumerate(inputs):
        lines = read_lines(path)
        if mode == "include" and index > 0:
            name = os.path.splitext(os.path.basename(path))[0]
            prefixed = []
            for line in lines:
                stripped = line.strip()
                if stripped.startswith("@"):
                    label = stripped.lstrip("@").strip().split()[0]
                    rest = stripped[len(label) + 1:].strip() if len(stripped) > len(label) + 1 else ""
                    line = f"@{name}.{label}" + (f" {rest}" if rest else "")
                prefixed.append(line)
            lines = prefixed
        start = len(merged)
        merged.extend(lines)
        boundaries.append((os.path.basename(path), start, len(merged)))
    return merged, boundaries


def generate_compiled(interpreter_source: str, source: list, files: list, inputs: list, mode: str) -> str:
    source_lines = "\n".join(f"    {line!r}," for line in source)
    files_lines = "\n".join(f"    ({name!r}, {start}, {end})," for name, start, end in files)
    sources_joined = ", ".join(inputs)
    return (
        "#!/usr/bin/env python3\n"
        "# -*- coding: utf-8 -*-\n"
        "# ============================================================\n"
        f"# Generated by BSYHC - Base SisYpH Compiler v{VERSION}\n"
        "# Do not edit by hand. Edit the .syh sources and recompile.\n"
        f"# Sources: {sources_joined}\n"
        f"# Merge mode: {mode}\n"
        "# ============================================================\n"
        "\n"
        f"{interpreter_source}\n"
        "SOURCE = [\n"
        f"{source_lines}\n"
        "]\n"
        "\n"
        "FILES = [\n"
        f"{files_lines}\n"
        "]\n"
        "\n"
        'if __name__ == "__main__":\n'
        "    import traceback\n"
        "    try:\n"
        "        execute_lines(SOURCE)\n"
        "    except Exception:\n"
        "        traceback.print_exc()\n"
    )


def compile_files(inputs: list, output: str, mode: str):
    interpreter_source = strip_main_block(open(INTERPRETER_FILE, "r", encoding="utf-8").read())
    source, files = merge_sources(inputs, mode)
    compiled = generate_compiled(interpreter_source, source, files, inputs, mode)
    with open(output, "w", encoding="utf-8") as f:
        f.write(compiled)
    print(f"BSYHC: compiled {len(inputs)} file(s) into '{output}' ({len(source)} lines).")


def extract_array(source_text: str, name: str) -> list:
    match = re.search(rf"^{name}\s*=\s*\[", source_text, re.MULTILINE)
    if not match:
        bsyhc_error(f"'{name}' array not found in the compiled file.")
    start = match.end() - 1
    depth = 0
    in_string = None
    escape = False
    i = start
    while i < len(source_text):
        ch = source_text[i]
        if in_string:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == in_string:
                in_string = None
        else:
            if ch in ("'", '"'):
                in_string = ch
            elif ch == "[":
                depth += 1
            elif ch == "]":
                depth -= 1
                if depth == 0:
                    try:
                        return ast.literal_eval(source_text[start:i + 1])
                    except (ValueError, SyntaxError) as e:
                        bsyhc_error(f"cannot parse '{name}' array: {e}")
        i += 1
    bsyhc_error(f"unterminated '{name}' array in the compiled file.")


def decompile_file(input_path: str, output: str, split: bool):
    if not os.path.isfile(input_path):
        bsyhc_error(f"File '{input_path}' not found.")
    with open(input_path, "r", encoding="utf-8") as f:
        text = f.read()
    source = extract_array(text, "SOURCE")
    files = extract_array(text, "FILES")
    if not files:
        files = [(os.path.basename(input_path), 0, len(source))]
    if not split:
        with open(output, "w", encoding="utf-8") as f:
            f.write("\n".join(source) + "\n")
        print(f"BSYHC: decompiled into '{output}' ({len(source)} lines).")
        return
    for name, start, end in files:
        path = os.path.join(output, name) if output else name
        os.makedirs(os.path.dirname(path), exist_ok=True) if os.path.dirname(path) else None
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(source[start:end]) + "\n")
        print(f"BSYHC: restored '{path}' ({end - start} lines).")


def interpret_file(input_path: str):
    if input_path.endswith(".py"):
        bsyhc_error(f"'{input_path}' is a Python file. Use -d to decompile it or run it with 'python3 {input_path}'.")
    lines = read_lines(input_path)
    interpreter = load_interpreter()
    interpreter["execute_lines"](lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="bsyhc.py",
        description="BSYHC - Base SisYpH Compiler: compile, decompile and interpret Sisyph (.syh) programs.",
        epilog="Examples:\n"
               "  python3 bsyhc.py -i b.syh -c -o bsyhc-test-b.py\n"
               "  python3 bsyhc.py -i bsyhc-test-b.py -d -o b-de.syh\n"
               "  python3 bsyhc.py -i b.syh",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("-i", "--input", action="append", metavar="FILE", required=True,
                        help="input file (repeat to compile several files into one output)")
    parser.add_argument("-o", "--output", metavar="FILE", help="output file (default: <input>.py / <input>.syh)")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("-c", "--compile", action="store_true", help="compile .syh into a self-contained .py")
    mode.add_argument("-d", "--decompile", action="store_true", help="decompile a compiled .py back into .syh")
    parser.add_argument("--merge", choices=["concat", "include"], default="concat",
                        help="how to merge several inputs: concat (default) or include (labels of extra files get 'name.' prefix)")
    parser.add_argument("--split", action="store_true",
                        help="with -d: restore each source file separately into the -o directory")
    parser.add_argument("--version", action="version", version=f"BSYHC v{VERSION}")
    return parser


def main():
    args = build_parser().parse_args()

    if args.compile:
        if args.split:
            bsyhc_error("--split is only valid with -d (decompile).")
        output = args.output or os.path.splitext(args.input[0])[0] + ".py"
        compile_files(args.input, output, args.merge)
    elif args.decompile:
        if len(args.input) != 1:
            bsyhc_error("-d accepts exactly one input file.")
        if args.split:
            output = args.output or "."
        else:
            output = args.output or os.path.splitext(args.input[0])[0] + ".syh"
        decompile_file(args.input[0], output, args.split)
    else:
        if len(args.input) != 1:
            bsyhc_error("interpret mode accepts exactly one input file. Use -c to compile several files.")
        interpret_file(args.input[0])


if __name__ == "__main__":
    main()